version: "3.7"
services:
 app:
  image: sofar123/price_server
  ports:
   - 9090:9090
  restart: unless-stopped
  depends_on:
   -  database
  environment:
   DB_HOST: database
   DB_PORT: 5432
   DB_USER: postgres
   DB_PASSWORD: postgres
   DB_NAME: pricedb

 database:
  image: postgres:latest
  ports:
   - 5432:5432
  restart: always
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: pricedb
  volumes:
   - ./init/:/docker-entrypoint-initdb.d/
#   - ~/etc/postgresql:/etc/postgresql
#   - ~/var/log/postgresql:/var/log/postgresql
#   - ~/var/lib/postgresql:/var/lib/postgresql
#   - ~/var/lib/postgresql/data:/var/lib/postgresql/data/:rw